# Generated by Django 5.2.4 on 2025-08-10 10:49

import account.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.manager.UserManager()),
            ],
        ),
    ]
